// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4T4cj80tYeFPXCJnAY-lP9FGjO3ara-Y',
    appId: '1:497931016895:web:548f6ad2f5cf56bc83840a',
    messagingSenderId: '497931016895',
    projectId: 'sliceit-124',
    authDomain: 'sliceit-124.firebaseapp.com',
    storageBucket: 'sliceit-124.firebasestorage.app',
    measurementId: 'G-DYQ74JFY79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6tU3ZSmXxtfWzk0v24DNKbETS5t9AbVI',
    appId: '1:497931016895:android:6ccdfd84a99529db83840a',
    messagingSenderId: '497931016895',
    projectId: 'sliceit-124',
    storageBucket: 'sliceit-124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2mjedpsHXAdBwqZSepVgGZWlPPAIu-E',
    appId: '1:497931016895:ios:f08e1a986502578c83840a',
    messagingSenderId: '497931016895',
    projectId: 'sliceit-124',
    storageBucket: 'sliceit-124.firebasestorage.app',
    iosBundleId: 'com.example.sliceit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2mjedpsHXAdBwqZSepVgGZWlPPAIu-E',
    appId: '1:497931016895:ios:f08e1a986502578c83840a',
    messagingSenderId: '497931016895',
    projectId: 'sliceit-124',
    storageBucket: 'sliceit-124.firebasestorage.app',
    iosBundleId: 'com.example.sliceit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4T4cj80tYeFPXCJnAY-lP9FGjO3ara-Y',
    appId: '1:497931016895:web:bfd002f2d4f52fd583840a',
    messagingSenderId: '497931016895',
    projectId: 'sliceit-124',
    authDomain: 'sliceit-124.firebaseapp.com',
    storageBucket: 'sliceit-124.firebasestorage.app',
    measurementId: 'G-L5E3W5NES3',
  );
}
